[package]
name = "adder_dp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-bitvec = "0.1.1"
itertools = "0.10.3"
rayon = "1.5.1"

