[package]
name = "adder_gui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
adder_algorithm = { path = "../algorithm" }
eframe = { version = "0.19.0", features = ["persistence"] }
egui = "0.19.0"
serde = { version = "1.0.148", features = ["serde_derive"] }
